// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Sovri SAS

import type { Finding, Review } from "@sovri/core";
import { describe, expect, it } from "vitest";

import { composeWalkthrough } from "./index.js";

const baseReview: Review = {
  id: "550e8400-e29b-41d4-a716-446655440000",
  pr_number: 36,
  repo_full_name: "mpiton/sovri",
  commit_sha: "a".repeat(40),
  started_at: new Date("2026-05-17T08:00:00.000Z"),
  completed_at: new Date("2026-05-17T08:01:00.000Z"),
  llm_provider: "test-provider",
  llm_model: "test-model",
  tokens_used: {
    prompt: 1200,
    completion: 300,
  },
  summary: "Findings are sorted deterministically.",
  findings: [],
  walkthrough_markdown: "Previous provider walkthrough.",
  status: "success",
};

const findingCatalog = {
  duplicatedCondition: finding({
    id: "11111111-1111-4111-8111-111111111111",
    severity: "minor",
    file: "src/review/zeta.ts",
    lineStart: 30,
    lineEnd: 30,
    title: "Duplicated condition",
  }),
  unvalidatedSessionToken: finding({
    id: "22222222-2222-4222-8222-222222222222",
    severity: "blocker",
    file: "src/auth/session.ts",
    lineStart: 42,
    lineEnd: 45,
    title: "Unvalidated session token",
  }),
  missingPayloadNullGuard: finding({
    id: "33333333-3333-4333-8333-333333333333",
    severity: "major",
    file: "src/review/alpha.ts",
    lineStart: 18,
    lineEnd: 18,
    title: "Missing payload null guard",
  }),
  missingInstallationCheck: finding({
    id: "44444444-4444-4444-8444-444444444444",
    severity: "major",
    file: "src/review/alpha.ts",
    lineStart: 10,
    lineEnd: 10,
    title: "Missing installation check",
  }),
  preferClearerVariableName: finding({
    id: "55555555-5555-4555-8555-555555555555",
    severity: "nitpick",
    file: "src/review/zeta.ts",
    lineStart: 9,
    lineEnd: 9,
    title: "Prefer clearer variable name",
  }),
  documentFallbackPath: finding({
    id: "66666666-6666-4666-8666-666666666666",
    severity: "info",
    file: "src/docs/comment.ts",
    lineStart: 2,
    lineEnd: 2,
    title: "Document fallback path",
  }),
} satisfies Record<string, Finding>;

describe("composeWalkthrough stable ordering", () => {
  it("renders identical markdown for two explicit shuffled finding inputs", () => {
    // Given review A findings are provided in this order
    const reviewA: Review = {
      ...baseReview,
      findings: [
        findingCatalog.duplicatedCondition,
        findingCatalog.unvalidatedSessionToken,
        findingCatalog.missingPayloadNullGuard,
        findingCatalog.missingInstallationCheck,
        findingCatalog.preferClearerVariableName,
        findingCatalog.documentFallbackPath,
      ],
    };
    // And review B findings are provided in this order
    const reviewB: Review = {
      ...baseReview,
      findings: [
        findingCatalog.documentFallbackPath,
        findingCatalog.missingInstallationCheck,
        findingCatalog.preferClearerVariableName,
        findingCatalog.unvalidatedSessionToken,
        findingCatalog.duplicatedCondition,
        findingCatalog.missingPayloadNullGuard,
      ],
    };

    // When the maintainer calls `composeWalkthrough(review A)`
    const markdownA = composeWalkthrough(reviewA);
    // And the maintainer calls `composeWalkthrough(review B)`
    const markdownB = composeWalkthrough(reviewB);

    // Then both markdown strings are identical
    expect(markdownA).toBe(markdownB);
    // And the output contains no current date
    expect(markdownA).not.toContain(new Date().toISOString().slice(0, 10));
    // And the output contains no random identifier generated by the composer
    expect(markdownA).not.toMatch(
      /\b[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b/u,
    );
  });
});

type FindingInput = {
  readonly id: string;
  readonly severity: Finding["severity"];
  readonly file: string;
  readonly lineStart: number;
  readonly lineEnd: number;
  readonly title: string;
};

function finding(input: FindingInput): Finding {
  return {
    id: input.id,
    severity: input.severity,
    category: "bug",
    file: input.file,
    line_start: input.lineStart,
    line_end: input.lineEnd,
    title: input.title,
    body: `Review details for ${input.title}.`,
    recommendation: `Address the issue in ${input.title}.`,
    source: "llm",
    confidence: 0.87,
  };
}
